// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfzuijskqjbtpckzzemh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmenVpanNrcWpidHBja3p6ZW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDY2NjIsImV4cCI6MjA3MTY4MjY2Mn0.WG3NRPHVB73kdq_IbdcYTCgDBRcaVVkRWvrdSJDEp8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});